import { Ad, AdCategory, AdType, AdStatus } from './types';

export const CATEGORIES: { value: AdCategory; label: string }[] = [
  { value: AdCategory.ENTERTAINMENT, label: 'Entertainment' },
  { value: AdCategory.SHOPPING, label: 'Shopping' },
  { value: AdCategory.AUTOMOTIVE, label: 'Automotive' },
  { value: AdCategory.TECHNOLOGY, label: 'Technology' },
  { value: AdCategory.TRAVEL, label: 'Travel' },
  { value: AdCategory.FOOD, label: 'Food & Drink' },
  { value: AdCategory.FINANCE, label: 'Finance' },
];

export const MOCK_ADS: Ad[] = [
  {
    id: 'ad-001',
    title: 'Dhoni: A Tribute',
    description: 'Relive the greatest moments of Captain Cool, M.S. Dhoni, and his journey with the Indian cricket team. A nostalgic trip for every cricket fan.',
    type: AdType.VIDEO,
    category: AdCategory.ENTERTAINMENT,
    reward: 2.50,
    duration: 30,
    contentUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://i.ytimg.com/vi/6665pybDB34/maxresdefault.jpg',
    country: 'India',
    state: 'Maharashtra',
    district: 'Mumbai City',
    lat: 19.0760,
    lng: 72.8777,
    rating: 4.5,
    ratingCount: 20,
    uploaderId: 'user-789',
    uploaderName: 'Amit Kumar',
    status: AdStatus.APPROVED,
  },
  {
    id: 'ad-002',
    title: 'Big Diwali Sale',
    description: 'Get ready for the biggest sale of the year! Unbelievable deals on electronics, fashion, and more. Celebrate Diwali with amazing savings.',
    type: AdType.IMAGE,
    category: AdCategory.SHOPPING,
    reward: 1.75,
    duration: 15,
    contentUrl: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/f83724107758783.5faa2b1c144b6.jpg',
    thumbnailUrl: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/f83724107758783.5faa2b1c144b6.jpg',
    country: 'India',
    state: 'Delhi',
    district: 'New Delhi',
    lat: 28.6139,
    lng: 77.2090,
    rating: 5,
    ratingCount: 50,
    uploaderId: 'user-101',
    uploaderName: 'Sunita Devi',
    status: AdStatus.APPROVED,
  },
  {
    id: 'ad-003',
    title: 'Explore the Himalayas',
    description: 'Book your next adventure with us. Trekking, camping, and breathtaking views await you in the heart of the Himalayas. Packages starting from ₹9,999.',
    type: AdType.VIDEO,
    category: AdCategory.TRAVEL,
    reward: 3.50,
    duration: 25,
    contentUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnailUrl: 'https://www.thestatesman.com/wp-content/uploads/2022/04/iStock-533966932.jpg',
    country: 'India',
    state: 'Himachal Pradesh',
    district: 'Kullu',
    lat: 32.0998,
    lng: 77.1082,
    rating: 4.2,
    ratingCount: 15,
    uploaderId: 'user-789',
    uploaderName: 'Amit Kumar',
    status: AdStatus.PENDING,
  },
  {
    id: 'ad-004',
    title: 'The Future is Electric - New EV Sedan',
    description: 'Introducing the all-new electric sedan. 0-100 in 3 seconds, 500km range, and futuristic design. Book a test drive today!',
    type: AdType.VIDEO,
    category: AdCategory.AUTOMOTIVE,
    reward: 4.50,
    duration: 45,
    contentUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: 'https://img.etimg.com/thumb/width-1200,height-900,imgsize-33758,resizemode-75,msid-96694858/industry/auto/auto-news/indias-electric-car-market-to-see-more-action-in-2023-with-new-launches.jpg',
    country: 'India',
    state: 'Karnataka',
    district: 'Bengaluru (Bangalore) Urban',
    lat: 12.9716,
    lng: 77.5946,
    rating: 4.8,
    ratingCount: 35,
    uploaderId: 'user-101',
    uploaderName: 'Sunita Devi',
    status: AdStatus.APPROVED,
  },
  {
    id: 'ad-005',
    title: 'New Smartphone Launch',
    description: 'Experience the next generation of mobile technology. Pre-order now for exclusive offers.',
    type: AdType.VIDEO,
    category: AdCategory.TECHNOLOGY,
    reward: 5.00,
    duration: 60,
    contentUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://i.gadgets360cdn.com/large/galaxy_s23_ultra_1675231223617.jpg',
    country: 'India',
    state: 'Karnataka',
    district: 'Bengaluru (Bangalore) Urban',
    rating: 0,
    ratingCount: 0,
    uploaderId: 'user-789',
    uploaderName: 'Amit Kumar',
    status: AdStatus.PENDING,
  },
  {
    id: 'ad-006',
    title: 'Gourmet Pizza Delivery',
    description: 'Hot, fresh, and delicious pizzas delivered to your doorstep in 30 minutes. Order now!',
    type: AdType.IMAGE,
    category: AdCategory.FOOD,
    reward: 1.50,
    duration: 10,
    contentUrl: 'https://www.kingarthurbaking.com/sites/default/files/2020-03/crispy-cheesy-pan-pizza.jpg',
    thumbnailUrl: 'https://www.kingarthurbaking.com/sites/default/files/2020-03/crispy-cheesy-pan-pizza.jpg',
    country: 'India',
    state: 'Maharashtra',
    district: 'Pune',
    rating: 0,
    ratingCount: 0,
    uploaderId: 'user-101',
    uploaderName: 'Sunita Devi',
    status: AdStatus.REJECTED,
    rejectionReason: 'Low quality image.',
  }
];