import { Ad, AdType, AdCategory } from "./types";

export const STARTING_BALANCE = 250.00;

export const MOCK_ADS: Ad[] = [
    {
        id: 'ad-001',
        type: AdType.VIDEO,
        title: 'Dhoni\'s Masterclass',
        description: 'Relive the iconic moments of MS Dhoni\'s legendary cricket career. A tribute to Captain Cool.',
        category: AdCategory.SPORTS,
        contentUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        thumbnailUrl: 'https://i.ytimg.com/vi/a_6v_7S0-4Y/maxresdefault.jpg',
        duration: 15,
        reward: 5.00,
        rating: 4.9,
        country: 'India',
        state: 'Maharashtra',
        district: 'Mumbai',
        lat: 19.0760,
        lng: 72.8777,
    },
    {
        id: 'ad-002',
        type: AdType.IMAGE,
        title: 'Diwali Dhamaka Sale',
        description: 'Get up to 70% off on electronics, fashion, and more this festive season. Celebrate Diwali with incredible savings!',
        category: AdCategory.FASHION_APPAREL,
        contentUrl: 'https://static.vecteezy.com/system/resources/previews/000/667/357/original/diwali-sale-banner-design-template.jpg',
        thumbnailUrl: 'https://static.vecteezy.com/system/resources/previews/000/667/357/original/diwali-sale-banner-design-template.jpg',
        duration: 10,
        reward: 3.50,
        rating: 4.7,
        country: 'India',
        state: 'Delhi',
        district: 'New Delhi',
        lat: 28.6139,
        lng: 77.2090,
    },
     {
        id: 'ad-003',
        type: AdType.VIDEO,
        title: 'Incredible India: Kerala',
        description: 'Explore the serene backwaters, lush green landscapes, and vibrant culture of Kerala, God\'s Own Country.',
        category: AdCategory.TRAVEL,
        contentUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        thumbnailUrl: 'https://www.keralatourism.org/images/enchanting_kerala/large/kerala_backwaters20210217115858_1074_1.jpg',
        duration: 15,
        reward: 6.00,
        rating: 4.8,
        country: 'India',
        state: 'Karnataka',
        district: 'Bengaluru',
        lat: 12.9716,
        lng: 77.5946,
    },
    {
        id: 'ad-004',
        type: AdType.IMAGE,
        title: 'Royal Enfield - Built Like a Gun',
        description: 'Experience the thrill of the open road with the timeless Royal Enfield Classic 350. Book a test ride today!',
        category: AdCategory.AUTOMOTIVE,
        contentUrl: 'https://www.royalenfield.com/content/dam/royal-enfield/india/motorcycles/classic-350/colors/studio-shots/new-studio-shots/stealth-black/01-stealth-black.png',
        thumbnailUrl: 'https://www.royalenfield.com/content/dam/royal-enfield/india/motorcycles/classic-350/colors/studio-shots/new-studio-shots/stealth-black/01-stealth-black.png',
        duration: 8,
        reward: 4.00,
        rating: 4.6,
        country: 'India',
        state: 'Tamil Nadu',
        district: 'Chennai',
        lat: 13.0827,
        lng: 80.2707,
    },
];

export const CATEGORIES: { value: AdCategory; label: string }[] = [
    { value: AdCategory.ENTERTAINMENT, label: 'Entertainment' },
    { value: AdCategory.FASHION_APPAREL, label: 'Fashion & Apparel' },
    { value: AdCategory.FOOD_BEVERAGE, label: 'Food & Beverage' },
    { value: AdCategory.TRAVEL, label: 'Travel' },
    { value: AdCategory.TECH, label: 'Technology' },
    { value: AdCategory.AUTOMOTIVE, label: 'Automotive' },
    { value: AdCategory.SPORTS, label: 'Sports' },
    { value: AdCategory.GAMING, label: 'Gaming' },
];